### ISSUE TITLE
Import NFT storefront from repository

### ISSUE THREAD

**Issue by turbolent** [onflow/flow-emulator#103]
### Issue To Be Solved

The emulator deploys several contracts by default, e.g. FT, NFT, etc. 

One of the contracts, the NFT storefront, is directly committed to / vendored in this repository in [`server/contracts/NFTStorefront.cdc`](https://github.com/onflow/flow-emulator/blob/master/server/contracts/NFTStorefront.cdc). 

However, the other contracts are imported as "normal" Go dependencies, as their source repositories provide the contract code in Go packages, e.g. https://github.com/onflow/flow-nft/blob/master/lib/go/contracts/contracts.go#L3.

### Suggested Solution

- Generate/provide contracts from the repository in https://github.com/onflow/nft-storefront/tree/main/lib/go
- Add a dependency on `github.com/onflow/nft-storefront` and get the contract source from it
- Remove `server/contracts/NFTStorefront.cdc`

**Comment by sideninja** [comment]
Fixed in https://github.com/onflow/flow-emulator/pull/182
