### ISSUE TITLE
provide an interface to query Emulator server status

### ISSUE THREAD

**Issue by kerrywei** [onflow/flow-emulator#111]
### Issue To Be Solved
It is a commonly encountered issue that there are intermittent failures for tests backed by flow-js-testing library, per described in https://github.com/onflow/flow-js-testing/issues/47. 
It turns out the root cause is that there is not a reliable way for processes to check whether the emulator is fully started, hence tests could be run before HTTP/gRPC servers are ready, causing failures. 

### Suggest A Solution
Rather than relying on [this logging line](https://github.com/onflow/flow-js-testing/blob/master/src/emulator.js#L108), there should be a reliable interface (i.e. maybe /status) provided by the emulator to reflect the status of the servers

**Comment by psiemens** [comment]
There are actually a couple ways to do this already.

An Access API client can call the [Ping](https://github.com/onflow/flow-emulator/blob/master/server/backend/backend.go#L64-L66) gRPC method, which returns OK if the gRPC server is running.

I don't advise using this one outside of a hosted environment (e.g. kubernetes cluster), but the emulator also has an HTTP liveness endpoint exposed that should work with `GET http://localhost:8080/live`. It returns 200 if the server is running.

**Comment by kerrywei** [comment]
> There are actually a couple ways to do this already.
> 
> An Access API client can call the [Ping](https://github.com/onflow/flow-emulator/blob/master/server/backend/backend.go#L64-L66) gRPC method, which returns OK if the gRPC server is running.
> 
> I don't advise using this one outside of a hosted environment (e.g. kubernetes cluster), but the emulator also has an HTTP liveness endpoint exposed that should work with `GET http://localhost:8080/live`. It returns 200 if the server is running.

Good callout @psiemens  👍 
Per our sync, here's what we will do: 
- update flow-js-testing library to use HTTP endpoint /ping (alpha version)
- update KittyItems to use this Alpha version of js testing lib, verify the correctness in CI environment
- once access node APIs have RESTful version in the emulator, change flow-js-testing lib to use /ping endpoint instead of /live

I'll close this one and open a new task under this repo to track the more comprehensive initiative -- "implementing RESTful APIs in emualtor"
