### ISSUE TITLE
Port RESTful APIs to emulator

### ISSUE THREAD

**Issue by kerrywei** [onflow/flow-emulator#113]
### Issue To Be Solved
Port the RESTful API we built for access node to the emulator

**Comment by sampullman** [comment]
I'm not sure if this is the right place to ask/discuss, but a useful addition to an emulator REST API could be end endpoint for fully resetting the state. In our integration/CI tests we rely on shutting down and resetting the process, but it would be more efficient (and easier from a containerized environment) if the emulator exposed an endpoint for doing this.

**Comment by sideninja** [comment]
@sampullman I think that is a great idea as part of the emulator management API, you should open this as a separate issue with feature/feedback tags, as this one is targeting migration of the new REST API.
