### ISSUE TITLE
Default contract deployment doesn't work on docker

### ISSUE THREAD

**Issue by arturenault** [onflow/flow-emulator#121]
### Problem
When running the emulator as a docker container and passing in FLOW_WITHCONTRACTS, none of the contracts are deployed. I see the following error in the logs.
```
ERRO[0000] ❗  Failed to deploy contracts                 error="not able to deploy contracts without set private key"
```
I'm not sure what is happening, since I am passing in the service private key.

### Steps to Reproduce
```
Deploy the emulator with the following environment variables:
      - FLOW_VERBOSE=true
      - FLOW_SIMPLEADDRESSES=true
      - FLOW_PERSIST=true
      - FLOW_WITHCONTRACTS=true
      - FLOW_SERVICEPRIVATEKEY=7304f85bf218f33430d43edfce2179effd227012632f97632e82587ffce2604e
      - FLOW_SERVICEPUBLICKEY=f458682be04790265e552251c391e0915a12f538cf871c20e1980f9caaf81cf02da7a0929d1f7d0e9524819b1b305a1910d3aa382cb8bb045341337e599872dc
      - FLOW_SERVICEKEYSIGALGO=ECDSA_P256
      - FLOW_SERVICEKEYHASHALGO=SHA3_256
```

### Acceptance Criteria
None

### Context
Blocks my local usage of the emulator.

**Comment by hotrungnhan** [comment]
me too

**Comment by sideninja** [comment]
What is the error? how do you run it?

**Comment by hotrungnhan** [comment]
> What is the error? how do you run it?

Just put both private key and it coresponse public key to docker env. And they dont work =)))

**Comment by sideninja** [comment]
Ok, will take a look into that today. Thank you for reporting.
