### ISSUE TITLE
Support non-local databases

### ISSUE THREAD

**Issue by KeisukeYamashita** [onflow/flow-emulator#130]
### Issue To Be Solved

Currently, the Badger is only supported as an DB and all the data are written to the local disk.
To use this emulator as a development network, in my company, we are planning to deploy this emulator and the dev wallet to the GKE cluster.

But since the Badger makes the workload stateful, we need to create a Statefulset with persistence volume to store the data.
It will make it easier to manage if the emulator can run in stateless manner because Kubernetes workloads are basically designed as stateless.

### (Optional): Suggest A Solution

I saw this article [Supporting digital ownership and decentralization with Dapper Labs and Google Cloud](https://cloud.google.com/blog/topics/startups/scaling-blockchain-and-nfts-with-google-cloud) saying that the Dapper, inc has now partnerships with GCP. 

Therefore, I think the best candidate will be Cloud Firestore, a NoSQL database from GCP.
I also considered Cloud Spanner but it's not KVS and it's quite expensive 💵

**Comment by sideninja** [comment]
I like this feature but I can't promise you a delivery date from our side. Hopefully, we can work on this soon, but you are also welcome to take a stab at it if you have the resources ofc.

**Comment by KeisukeYamashita** [comment]
Hi, I didn't intend to assign someone for this, I wanted to know the communities and the maintainers opinion and opened a ticket. Thank you for your reply!

**Comment by bluesign** [comment]
I think we can close this as now we support redis backend.
