### ISSUE TITLE
Missing http://localhost:8701/api/ 

### ISSUE THREAD

**Issue by SCMPJeffLeung** [onflow/flow-emulator#140]
### Instructions

Please fill out the template below to the best of your ability and include a label indicating which tool/service you were working with when you encountered the problem.

### Problem
this requesting a not exisit api http://localhost:8701/api/ 
https://github.com/onflow/fcl-dev-wallet/blob/main/contexts/ConfigContext.tsx#L22

but the /api was removed since after version 0.3.4
https://github.com/onflow/fcl-dev-wallet/tree/main/pages
https://github.com/onflow/fcl-dev-wallet/tree/v0.3.4/pages

<what is the problem you've encountered?>

### Steps to Reproduce

<share any logs/screenshots or steps to replicate>

### Acceptance Criteria

<if any>

### Context

<what are you currently working on that this is blocking?>

**Comment by sideninja** [comment]
Hey, that was moved to the new version of the CLI, you can now use `flow dev-wallet` feature on the CLI to run the FCL Dev wallet: https://github.com/onflow/flow-cli/releases/tag/v0.32.0

**Comment by sideninja** [comment]
But I apologise @SCMPJeffLeung we should remove this feature more gradually and deprecate it first.
