### ISSUE TITLE
Implement unimplemented grpc API methods

### ISSUE THREAD

**Issue by janezpodhostnik** [onflow/flow-emulator#141]
## Instructions

The new grpc endpoints just panic if called:

- `GetTransactionResultByIndex`
- `GetTransactionsByBlockID`
- `GetTransactionResultsByBlockID`

### Issue To Be Solved

Implement the new grpc endpoints added here: 
- [Create RPC endpoints for GetTransactionResultByIndex in AN and EN](https://github.com/onflow/flow/pull/875)
- [Add GetTransactionResultsByBlockID for EN API](https://github.com/onflow/flow/pull/912)

**Comment by bluesign** [comment]
I checked this, even wrote the implementation, but then I saw flow-go-sdk and fcl-js also doesn't implement those. 

Do we really need them ? @janezpodhostnik @sideninja 

If we need them, does REST API also support them ?
