### ISSUE TITLE
Push latest emulator image that works with Secure Cadence release

### ISSUE THREAD

**Issue by onkel-skrue** [onflow/flow-emulator#147]
Push latest emulator image that works with [Secure Cadence](https://forum.onflow.org/t/breaking-changes-coming-with-secure-cadence-release/3052) changes to docker registry. I need to run the emulator in my docker-compose stack with the breaking changes mentioned in the forum.

**Comment by j1010001** [comment]
Hi @onkel-skrue, we are working on new secure cadence build and will push emulator build for it, ETA in the next 1-2 days.

**Comment by j1010001** [comment]
Hi @onkel-skrue, you should be able to pull the emulator image now: `docker pull gcr.io/flow-container-registry/emulator:0.31.1-sc `
