### ISSUE TITLE
Start emulator with custom zerolog to log out debug information

### ISSUE THREAD

**Issue by bjartek** [onflow/flow-emulator#162]
## Instructions

In the following Thread in discord @janezpodhostnik gave some very nice debug information about a transaction [984648422780981278](https://discord.com/channels/613813861610684416/984648422780981278/987104559413460992)

Testnet:
ComputationKindStatement: 2111,
ComputationKindLoop: 150,
ComputationKindFunctionInvocation: 605,
ComputationKindGetValue: 134858,
ComputationKindSetValue: 185044

Mainnet:
ComputationKindStatement: 2561,
ComputationKindLoop: 150,
ComputationKindFunctionInvocation: 755,
ComputationKindGetValue: 396052,
ComputationKindSetValue: 434249,

It would be very nice if this information was present in the emualtor. If nothing else then as log messages

### Issue To Be Solved

Adding an option to allow starting emulator with a custom zerolog implementation.

https://github.com/onflow/flow-emulator/blob/master/blockchain.go#L364

**Comment by bluesign** [comment]
Closed with https://github.com/onflow/flow-emulator/pull/166 

We can close this issue
