### ISSUE TITLE
Push latest to docker repository

### ISSUE THREAD

**Issue by onkel-skrue** [onflow/flow-emulator#163]
Could you push latest version to docker repository? I am using `emulator:latest`, but getting `404` when requesting `http://localhost:8701/api`. Workaround is to use fcl cli to run the emulator, but I prefer docker. 

Note, I tried to build the image myself from `/cmd/emulator`, but getting error:
```
=> ERROR [build-app 6/6] RUN --mount=type=ssh     --mount=type=cache,target=/go/pkg/mod     --mount=type=cache,target=/root/.cache/go-build   0.2s
------
 > [build-app 6/6] RUN --mount=type=ssh     --mount=type=cache,target=/go/pkg/mod     --mount=type=cache,target=/root/.cache/go-build     GO111MODULE=on CGO_ENABLED=0 GOOS=linux GOARCH=arm64     go build -ldflags "-extldflags -static" -o ./app ./cmd/emulator:
#16 0.171 go: go.mod file not found in current directory or any parent directory; see 'go help modules'
------
executor failed running [/bin/sh -c GO111MODULE=on CGO_ENABLED=0 GOOS=$TARGETOS GOARCH=$TARGETARCH     go build -ldflags "-extldflags -static" -o ./app ./cmd/emulator]: exit code
```

**Comment by onkel-skrue** [comment]
My bad, latest changes were already pushed to the docker repository. But, I am still wondering why `/api` is not found. This is not the case when running the emulator via the cli. What is the difference?

**Comment by onkel-skrue** [comment]
np, I hope you are well. I am running dev-wallet and emulator with docker. I did a mistake. `/api` is an endpoint in dev-wallet, not the emulator.

**Comment by onkel-skrue** [comment]
@sideninja  Do you know why `/api` does not exist in `ghcr.io/onflow/fcl-dev-wallet:latest`? Should I open an issue there?

**Comment by onkel-skrue** [comment]
So I can't just run fcl-dev-wallet with docker-compose? I remember that this worked before. What is the point of `ghcr.io/onflow/fcl-dev-wallet` then?

**Comment by onkel-skrue** [comment]
I changed `FLOW_ACCESS_NODE=http://emulator:8888` to `FLOW_ACCESS_NODE=http://localhost:8888` and everything worked xD Thanks for your time :)

**Comment by sideninja** [comment]
Great that it works. Anytime.
