### ISSUE TITLE
Add flag to toggle transaction & gas fees

### ISSUE THREAD

**Issue by psiemens** [onflow/flow-emulator#17]
### Issue To Be Solved

Fees are optional in FVM, but this option isn't exposed to users of the emulator. This would be useful for developers who want to experiment with the emulator without worrying about fees.

### Suggest A Solution

```
flow emulator start --disable-fees
```

or 

```
flow emulator start --disable-tx-fees --disable-account-fees --disable-storage-fees
```

**Comment by sideninja** [comment]
This has been implemented with `--transaction-fees` flag
