### ISSUE TITLE
Emulator snapshot logs emitted to stderr instead of stdout

### ISSUE THREAD

**Issue by bartolomej** [onflow/flow-emulator#196]
### Issue To Be Solved

When emulator snapshot endpoint (`GET /emulator/snapshot/{name}`) is called, the emulator emits below logs to STDERR:
```
2022/08/31 03:04:51 http: superfluous response.WriteHeader call from github.com/onflow/flow-emulator/server.EmulatorAPIServer.Snapshot (emulator.go:129)
```

As far as I can tell those logs look more like "debug" logs - don't represent anything critical. Because of that, they should probably be emitted to STDOUT instead of STDERR.

### Suggest A Solution

If what I've written above is indeed the case, I think we should emit those logs to STDOUT instead of STDERR.

### Context

This would be a pretty minor improvement, but could be helpfull for programmatic detection of errors. 

We are currently working on adding snapshot management functionality to [Flowser app](https://github.com/onflowser/flowser), and we interprate any data that's emitted to STDERR to be an emulator error. But that's not probably the case with the above log, so this could confuse our users into thinking there is something wrong with flow emulator (we show an error dialog when such error is detected).

https://github.com/onflowser/flowser/pull/90

**Comment by bluesign** [comment]
this is actually an error ( server trying to write header after body) , I will investigate.

**Comment by bluesign** [comment]
thanks @bartolomej, I totally missed this somehow, made a PR https://github.com/onflow/flow-emulator/pull/197
