### ISSUE TITLE
Cadence error messages are difficult to read

### ISSUE THREAD

**Issue by psiemens** [onflow/flow-emulator#20]
### Issue To Be Solved

Cadence error messages are condensed onto a single line and don't include line numbers, making it difficult to use them for debugging.

### Suggest A Solution

Given that the emulator has access to the underlying Cadence errors from each transaction/script, we could use the attached line number data to create a readable printout for each error. If possible, it'd be great to show a snippet of the code near the error location.

**Comment by sideninja** [comment]
The error is now outputted as:
```
 --> 4d4fd0c5fd13fd56122ec827f96872fd5eb0951dbaa2ad5f8446545770fd7350:5:2
  |
5 | 		panic("test")
  |   ^^^^^^^^^^^^^ 
```
and I believe this closes the issue.
