### ISSUE TITLE
Snapshot creation fails on latest emulator version (flow-cli v0.40.0)

### ISSUE THREAD

**Issue by bartolomej** [onflow/flow-emulator#204]
### Problem

I installed the latest version of flow-cli and ran the emulator with the appropriate flags for using snapshot feature (`--persist`).

But when I tried creating a snapshot, I received a 500 (Internal Server Error) response.

### Steps to Reproduce

Run flow emulator and try to create a snapshot with below commands.

Emulator command:

```bash
➜ git:(ui_fixes_15_9) ✗ flow emulator --verbose --persist
INFO[0000] ⚙️   Using service account 0xf8d6e0586b0a20c7  serviceAddress=f8d6e0586b0a20c7 serviceHashAlgo=SHA3_256 servicePrivKey=0660f98a97d73a374bab87d5b21d06a2a9285e6a71ca75babec113badb6ba58c servicePubKey=588e7f586822522b63e350f47efd9dd51fc04981614eb9eec55a6733dfe14a0de8fa9b53909120dd9dd4bd39ca16322d0d0708705f53ba3b76a90806246f0885 serviceSigAlgo=ECDSA_P256
INFO[0000] 📜  Flow contract                              FlowStorageFees=0xf8d6e0586b0a20c7
INFO[0000] 📜  Flow contract                              FlowServiceAccount=0xf8d6e0586b0a20c7
INFO[0000] 📜  Flow contract                              FlowToken=0x0ae53cb6e3f42a79
INFO[0000] 📜  Flow contract                              FungibleToken=0xee82856bf20e2aa6
INFO[0000] 📜  Flow contract                              FlowFees=0xe5a8b7f23e8b548f
INFO[0000] 🌱  Starting gRPC server on port 3569          port=3569
INFO[0000] 🌱  Starting REST API on port 8888             port=8888
INFO[0000] 🌱  Starting admin server on port 8080         port=8080
```

Snapshot creation command:

```bash
➜  git:(ui_fixes_15_9) ✗ http http://localhost:8080/emulator/snapshot/test
HTTP/1.1 500 Internal Server Error
Content-Length: 0
Content-Type: application/json
Date: Fri, 16 Sep 2022 11:39:45 GMT
```

### Acceptance Criteria

We discovered this issue when testing the "snapshot management" feature of the new flowser desktop app (https://github.com/onflow/developer-grants/issues/27).

**Comment by bluesign** [comment]
--persist and --snapshot separated as 2 flags.

**Comment by bartolomej** [comment]
Ohh, I see! Wasn't aware of that change.

Adding a link to that PR for reference: https://github.com/onflow/flow-emulator/pull/190

It might be worth emitting some kind of warning log next time. Something like "Failed to create snapshot, did you use the `--snapshot` flag".

**Comment by bartolomej** [comment]
Confirming that snapshots work with `--snapshot` flag mentioned above. Closing this issue.

**Comment by bluesign** [comment]
You are totally right, I missed that somehow, will try to make a PR for it ASAP.
