### ISSUE TITLE
Output Script Computational Cost 

### ISSUE THREAD

**Issue by ph0ph0** [onflow/flow-emulator#205]
### Issue To Be Solved

Scripts are as important for blockchain apps as transactions. Scripts have a computational limit (100k apparently, but I'm not sure what this refers to or how it is calculated), but it is not possible to view the computational cost in the emulator during development. Whether or not the 100k limit is considered high or sufficient for most scripts, it would be very beneficial to be able to see the 'cost' of a script in the emulator output.

**Comment by sideninja** [comment]
Good idea. cc @janezpodhostnik

**Comment by bluesign** [comment]
I started a gas usage analyzer for emulator btw, but in the meantime meter exposed from fvm would greatly help.
