### ISSUE TITLE
[FEATURE] Multi tenant emulator 

### ISSUE THREAD

**Issue by bluesign** [onflow/flow-emulator#207]
### Issue To Be Solved

In some cases, multi-tenant support can be valuable to emulator. One emulator instance, running multiple blockchains. 

I opened this issue for to start a discussion, if it is needed like I suspect, I can do the implementation.

**Comment by sideninja** [comment]
Should we close or leave as an idea if it gets traction?

**Comment by bluesign** [comment]
@sideninja 
I think we can close, I think solution outside emulator makes sense
