### ISSUE TITLE
Emulator GUI

### ISSUE THREAD

**Issue by psiemens** [onflow/flow-emulator#21]
What if the emulator shipped with a GUI? 

This is just an idea for now -- let's use this issue to evolve it further.

I find a block explorer to be very useful during testnet development because it allows me to easily _observe_ the state of the blockchain. There's currently no tool that makes it easy to observe the state of a locally-running emulator. 

What's the minimal version of an emulator GUI? Could it be a light block explorer that consumes the Access API, or should it also have the ability to control (start, stop, configure) the emulator?

**Comment by janezpodhostnik** [comment]
It would be cool to somehow also use FlowViewSource with the emulator...

**Comment by sideninja** [comment]
Closing in favour of buildathlon task.
