### ISSUE TITLE
[FEATURE] No History

### ISSUE THREAD

**Issue by bluesign** [onflow/flow-emulator#219]
### Issue To Be Solved

In some projects, we don't care about old chain history ( playground, testing etc ) I am thinking a flag ( actually, I have one I implemented as --no-past ) but looking for a nicer name.

This flag will prevent `script execution` and `getAccount` on previous blocks, but it will save a lot of space and memory.

**Comment by bluesign** [comment]
@sideninja, do you have any comment on this? should I make a PR? I think it is also a good update for the playground backend.

**Comment by bluesign** [comment]
I mean the register history, as far as I understand, we have something like this:

- Let's say I have String "deniz" in storage/test ( at block 1 ) 
- at block 2 I delete this, and make it "sideninja" 

this "deniz" stays forever in the database/memory.

**Comment by sideninja** [comment]
I understand. Do you think that's valuable just in terms of space optimization? also, where do you see this playing an important role?

**Comment by bluesign** [comment]
it saves a lot of space, I think mostly CI jobs ( big tests, low memory CI, etc.) Also, it has good synergy with the snapshot feature, we can have tiny snapshots. ( I am planning also sqlite backend support for the emulator as backend changes are merged ) I don't think executeScriptAtBlock is used that much tbh.

**Comment by bluesign** [comment]
I think this will not be too much saving in the short run, and will conflict with rollback. so closing.
