### ISSUE TITLE
Split snapshot management into multiple HTTP endpoints

### ISSUE THREAD

**Issue by bartolomej** [onflow/flow-emulator#228]
### Issue To Be Solved

Currently, there is a single endpoint for managing emulator snapshots: 
https://github.com/onflow/flow-emulator/blob/937995270076dd8d48a25df39d8f509c89bfec93/server/emulator.go#L90-L137

This endpoint performs multiple actions:
1. Creates a new snapshot
2. Jumps to an existing snapshot
3. Retrieves an existing snapshot

I think this is not ideal because:
1. It's confusing from the API consumer standpoint
4. Adds unnecessary API usage constraints, like:
   - API consumers can't check if the snapshot exists without risking that this will also trigger the "move state to snapshot" action
   - ...?

### Suggest A Solution

I think it would make sense to split those actions into separate REST endpoints:

1. `POST /emulator/snapshots/{name}` - create (or reverts to existing) snapshot
2. `PUT /emulator/snapshots/{name}` - revert to an existing snapshot (optional - could also work to just combine 1. and 2. into a single endpoint)
3. `GET /emulator/snapshots/{name}` - retrieve existing snapshot

### Context

This improvement would allow better snapshot management in [Flowser desktop app](https://github.com/onflowser/flowser), as it would allow us to:
- better handle snapshot errors and help discover unexpected bugs (an example of such bug is https://github.com/onflow/flow-emulator/issues/227)
- check whether the snapshots that were created (which are also stored/cached in our database) still exist at different points in time (e.g. user could manually remove `flowdb` folder, introducing a state conflict)

**Comment by bluesign** [comment]
@bartolomej thanks for this idea, I agree this is more useful. I will make a PR asap.

**Comment by bluesign** [comment]
@bartolomej I am thinking about this, I think we need 2 cases:

- Create ( or jump if exists )  
- Jump to existing ( error 404 if not exists ) 

Do we need something like, error if already exists case for create ?

**Comment by bartolomej** [comment]
@bluesign I think that if possible it would be good to have each HTTP endpoint & verb do only one thing (e.g. only create, only jump to an existing snapshot, or only retrieve existing snapshot if present) instead of multiple (e.g. create or jump if exists) - where the action that's eventually performed depends on the current state of the system.

I'm thinking this purely from the API design/usage perspective - e.g. it might lead to fewer bugs on the consumer's side? Although I'm open to either option.

One thing that is however necessary is the ability to check if some snapshot exists (e.g. using a get single: `GET /snapshots/{snapshotID}` or get multiple: `GET /snapshots` endpoints - the second option is even more preferable due to the reasons explained below) without performing any side-effect/action (e.g. jumping to snapshot if exists - as the current endpoint GET does).

That's necessary because clients may cache the created snapshots on their end and therefore need a way to check whether some snapshot still exists (e.g. wasn't removed by removing the `flowdb` folder manually) in order to show a correct state in the UI for example.

Flowser app currently uses the caching approach in this way. When the user creates a snapshot through our UI/API, we store the created snapshot in our DB and provide the user an option to later jump to that snapshot. We are not aware of any changes that are made to the emulator snapshots state outside Flowser - which could lead to out-of-sync states. That's why it could be beneficial to also have the "retrieve all existing snapshots" (`GET /snapshots`) endpoint - clients could poll that endpoint and update the local snapshot cache (or remove the need for it entirely).

Does this problem make sense? 

This approach wouldn't be backward compatible, but maybe it's worth implementing? What do you think?

**Comment by bluesign** [comment]
`GET /snapshots` to list all snapshots, in any case we should add, I guess, it seems pretty nice to have. 
`GET /snapshots/{snapshotID}` Retrieve existing one is also not a problem. ( also 404 on fail ) 

Only problem currently, after `create` we automatically jump to new context ( as we are using git on backend ) So we would need to jump back, which can complicate things a bit. 

Maybe we can add `PUT /snapshots/{snapshotID}` to create and error if exists. ( it will continue with new context if succeeds )

**Comment by bartolomej** [comment]
Oh, I see. If it's not possible (or too complicated) to just create a snapshot without jumping to it, I think that behavior is fine as long as there is a way to check for the existence of a snapshot (with `GET` endpoints that you mentioned)!
