### ISSUE TITLE
Cannot deploy contract to flow-container-registry/emulator which version is later than 0.34.1

### ISSUE THREAD

**Issue by LemonNekoGH** [onflow/flow-emulator#230]
### Problem
Cannot deploy contract to flow-container-registry/emulator which version is later than 0.34.1
The command report this error: 
```
❌ Command Error: client: rpc error: code = Unavailable desc = connection closed before server preface received
```

### Steps to Reproduce
1. run `docker run -p 3569:3569 -e <your key> gcr.io/flow-container-registry/emulator:0.35.0`
2. switch to a directory that contains contract and `flow.json`
3. run `flow deploy`

### Context
I am running a GitHub Actions to testing my Golang library. And used latest image version.
Here is failed job: https://github.com/LemonNekoGH/godence/actions/runs/3367714152/jobs/5585471784
I tryed to use [docker registry](https://gcr.io/v2/flow-container-registry/emulator/tags/list) API to get all tags of this image, and try to use every version on my local computer, I found `0.34.1` version that is no problem.

**Comment by bluesign** [comment]
Thanks for reporting @LemonNekoGH 

I will investigate and try to fix asap. 

self note: probably this is related to this commit:  https://github.com/onflow/flow-emulator/commit/c2f513a6b766ac142850a045b7c6ad0664fb225e

**Comment by sideninja** [comment]
This is due the host changing to `127.0.0.1` which in case of docker image you need to specify as using flag `--host 0.0.0.0`.  I made a PR to clarify that.
