### ISSUE TITLE
Enable multiple emulator instances for Playground

### ISSUE THREAD

**Issue by DylanTinianov** [onflow/flow-emulator#249]
### Instructions
After updating the flow-emulator dependency to v0.38.0 onward, flow-playground-api CI tests are failing.

### Problem

It's possible that the new implementation of Badger storage is breaking flow-playground-api. Playground has multiple instances of emulators running which could be an issue?

Previously playground was working fine with the older memstore storage implementation. Either changing to Badger, updating other dependencies (Cadence v0.28.0, flow-go-sdk v0.29.0, flow-go a3f3a87), or FVM changes broke things.

**Comment by bluesign** [comment]
I think this is related to accidental persist PR. #248

**Comment by fotescodev** [comment]
@DylanTinianov can we close this issue?
