### ISSUE TITLE
Error when reverting to a blockchain snapshot

### ISSUE THREAD

**Issue by bartolomej** [onflow/flow-emulator#252]
### Problem

I used the `/emulator/snapshot/{snapshotId}` to create and later revert to a snapshot of the blockchain state.

However, when trying to revert to an existing snapshot, the emulator encountered the following error:

```
2022/12/13 21:59:05 http: panic serving 127.0.0.1:58190: runtime error: invalid memory address or nil pointer dereference
```

<details>
<summary>Full error</summary>
<pre>
2022/12/13 21:59:05 http: panic serving 127.0.0.1:58190: runtime error: invalid memory address or nil pointer dereference
goroutine 146720 [running]:
net/http.(*conn).serve.func1()
/usr/local/go/src/net/http/server.go:1850 +0xb0
panic({0x1026f7000, 0x10360c600})
/usr/local/go/src/runtime/panic.go:890 +0x258
github.com/dgraph-io/badger/v2/skl.(*Skiplist).IncrRef(...)
/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.2007.4/skl/skl.go:86
github.com/dgraph-io/badger/v2.(*DB).getMemTables(0x140007f2c00)
/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.2007.4/db.go:626 +0x108
github.com/dgraph-io/badger/v2.(*DB).get(0x140007f2c00, {0x14012b5ad00, 0x35, 0x35})
/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.2007.4/db.go:661 +0x64
github.com/dgraph-io/badger/v2.(*Txn).Get(0x14012b702d0, {0x14012a87a40, 0x2d, 0x30})
/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.2007.4/txn.go:471 +0x218
github.com/onflow/flow-emulator/storage/badger.getTx.func1({0x14012a87a40?, 0x14012a87a10?, 0x2d?})
/go/pkg/mod/github.com/onflow/flow-emulator@v0.40.0/storage/badger/store.go:87 +0x34
github.com/onflow/flow-emulator/storage/badger.(*Store).GetBytes.func1(0x140007f2c00?)
/go/pkg/mod/github.com/onflow/flow-emulator@v0.40.0/storage/badger/store.go:102 +0xd8
github.com/dgraph-io/badger/v2.(*DB).View(0x14000074480?, 0x140065f69a8)
/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.2007.4/txn.go:802 +0x9c
github.com/onflow/flow-emulator/storage/badger.(*Store).GetBytes(0x103e19878?, {0x101f3dec1?, 0x14000074480?}, {0x101f3dec1?, 0x0?}, {0x14011419d70?, 0x140065f6a58?, 0x101a67ad0?})
/go/pkg/mod/github.com/onflow/flow-emulator@v0.40.0/storage/badger/store.go:101 +0x7c
github.com/onflow/flow-emulator/storage.(*DefaultStore).LatestBlockHeight(0x14000472000, {0x102994020, 0x14000124008})
/go/pkg/mod/github.com/onflow/flow-emulator@v0.40.0/storage/store.go:154 +0xb4
github.com/onflow/flow-emulator/storage.(*DefaultStore).LatestBlock(0x14000472000, {0x102994020, 0x14000124008})
/go/pkg/mod/github.com/onflow/flow-emulator@v0.40.0/storage/store.go:163 +0x44
github.com/onflow/flow-emulator.(*Blockchain).GetLatestBlock(0x140070f8000)
/go/pkg/mod/github.com/onflow/flow-emulator@v0.40.0/blockchain.go:623 +0x60
github.com/onflow/flow-emulator/server/backend.(*Backend).GetLatestBlock(0x140000db4a0, {0x2020200a0a29746e?, 0x2020202020202020?}, 0x20?)
/go/pkg/mod/github.com/onflow/flow-emulator@v0.40.0/server/backend/backend.go:133 +0x38
github.com/onflow/flow-emulator/server/backend.(*Adapter).GetLatestBlock(0x140065f6f88?, {0x102994090?, 0x14012b6a870?}, 0x20?)
/go/pkg/mod/github.com/onflow/flow-emulator@v0.40.0/server/backend/adapter.go:63 +0x28
github.com/onflow/flow-go/engine/access/rest.(*blockProvider).getBlock(0x14012b6a9f0, {0x102994090?, 0x14012b6a870?})
/go/pkg/mod/github.com/onflow/flow-go@v0.28.1-0.20221114195106-8bf6b00e6fbd/engine/access/rest/blocks.go:207 +0xfc
github.com/onflow/flow-go/engine/access/rest.getBlock(0x140065f72d8?, 0x14012b66300, {0x1029b1150?, 0x140005827e0}, {0x10299f000, 0x140005827f8})
/go/pkg/mod/github.com/onflow/flow-go@v0.28.1-0.20221114195106-8bf6b00e6fbd/engine/access/rest/blocks.go:119 +0xe4
github.com/onflow/flow-go/engine/access/rest.GetBlocksByHeight(0x14012b66300, {0x1029b1150, 0x140005827e0}, {0x10299f000, 0x140005827f8})
/go/pkg/mod/github.com/onflow/flow-go@v0.28.1-0.20221114195106-8bf6b00e6fbd/engine/access/rest/blocks.go:45 +0xc4
github.com/onflow/flow-go/engine/access/rest.(*Handler).ServeHTTP(0x14000683cc0, {0x1029903f0?, 0x14012b3b728}, 0x14012b72400)
/go/pkg/mod/github.com/onflow/flow-go@v0.28.1-0.20221114195106-8bf6b00e6fbd/engine/access/rest/handler.go:77 +0x35c
github.com/onflow/flow-go/engine/access/rest/middleware.commonQueryParamMiddleware.func1.1({0x1029903f0, 0x14012b3b728}, 0x14012b72400)
/go/pkg/mod/github.com/onflow/flow-go@v0.28.1-0.20221114195106-8bf6b00e6fbd/engine/access/rest/middleware/common_query_params.go:28 +0xec
net/http.HandlerFunc.ServeHTTP(0x14012b72300?, {0x1029903f0?, 0x14012b3b728?}, 0x102623c40?)
/usr/local/go/src/net/http/server.go:2109 +0x38
github.com/onflow/flow-go/engine/access/rest/middleware.commonQueryParamMiddleware.func1.1({0x1029903f0, 0x14012b3b728}, 0x14012b72300)
/go/pkg/mod/github.com/onflow/flow-go@v0.28.1-0.20221114195106-8bf6b00e6fbd/engine/access/rest/middleware/common_query_params.go:28 +0xec
net/http.HandlerFunc.ServeHTTP(0x0?, {0x1029903f0?, 0x14012b3b728?}, 0x101de1530?)
/usr/local/go/src/net/http/server.go:2109 +0x38
github.com/onflow/flow-go/engine/access/rest/middleware.LoggingMiddleware.func1.1({0x102992d30?, 0x14012b647e0}, 0x14012b72300)
/go/pkg/mod/github.com/onflow/flow-go@v0.28.1-0.20221114195106-8bf6b00e6fbd/engine/access/rest/middleware/logging.go:21 +0xbc
net/http.HandlerFunc.ServeHTTP(0x14012b72200?, {0x102992d30?, 0x14012b647e0?}, 0x52a3e4f439aad8dc?)
/usr/local/go/src/net/http/server.go:2109 +0x38
github.com/gorilla/mux.(*Router).ServeHTTP(0x1400046c480, {0x102992d30, 0x14012b647e0}, 0x14012b72100)
/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0x19c
github.com/rs/cors.(*Cors).Handler.func1({0x102992d30, 0x14012b647e0}, 0x14012b72100)
/go/pkg/mod/github.com/rs/cors@v1.8.0/cors.go:219 +0x1e4
net/http.HandlerFunc.ServeHTTP(0x14012b5ac8f?, {0x102992d30?, 0x14012b647e0?}, 0x101193d98?)
/usr/local/go/src/net/http/server.go:2109 +0x38
net/http.serverHandler.ServeHTTP({0x14012b6a660?}, {0x102992d30, 0x14012b647e0}, 0x14012b72100)
/usr/local/go/src/net/http/server.go:2947 +0x2c4
net/http.(*conn).serve(0x14012b681e0, {0x102994090, 0x140006accf0})
/usr/local/go/src/net/http/server.go:1991 +0x560
created by net/http.(*Server).Serve
/usr/local/go/src/net/http/server.go:3102 +0x444
</pre>
</details>

### Steps to Reproduce

I wasn't able to reliably reproduce this issue, as it doesn't happen on every attempt.

### Context

I'm testing Flowser app: https://flowser.dev

**Comment by sideninja** [comment]
cc @bluesign you mind looking into it?

**Comment by bluesign** [comment]
@sideninja I am out of town but back on Monday, I will debug first thing

**Comment by bluesign** [comment]
I tried to reproduce this but couldn't manage yet. I think badger corruption somehow. I think sqlite backend will solve this problem though.

**Comment by sideninja** [comment]
@bartolomej @bluesign any conclusion on next steps? Maybe @bartolomej check if it works using some other storage. Is Sqlite possible @bluesign ?

**Comment by bluesign** [comment]
should be fixed with new snapshot backend.
