### ISSUE TITLE
Implement block status for Acces API block functions

### ISSUE THREAD

**Issue by turbolent** [onflow/flow-emulator#254]
### Issue To Be Solved

#253 updated to the latest flow-go, which added an additional block status return value for Access API block functions. The PR only stubs the implementation, i.e. returns the status "unknown".

### Suggest A Solution

If possible, return the proper block status.

**Comment by bluesign** [comment]
We have a lot of stub grpc functions, I mentioned them before but didn't get any answer. https://github.com/onflow/flow-emulator/issues/141#issuecomment-1243341851

**Comment by bluesign** [comment]
@janezpodhostnik  I think we can safely return here BlockStatusSealed ( I started a PR ), is there any case I missed ?
