### ISSUE TITLE
Add updated standard contracts to those deployed by default when emulator runs

### ISSUE THREAD

**Issue by sisyphusSmiling** [onflow/flow-emulator#310]
### Issue To Be Solved

Currently, core contracts deployed to the emulator's service account include the following:

```
INFO[0000] 📜  Flow contract                              FlowServiceAccount=0xf8d6e0586b0a20c7
INFO[0000] 📜  Flow contract                              FlowToken=0x0ae53cb6e3f42a79
INFO[0000] 📜  Flow contract                              FungibleToken=0xee82856bf20e2aa6
INFO[0000] 📜  Flow contract                              FlowFees=0xe5a8b7f23e8b548f
INFO[0000] 📜  Flow contract                              FlowStorageFees=0xf8d6e0586b0a20c7
```

However, other standard contracts are often used by builders that they will inevitably need to import to their project.

### Suggest A Solution

Include the following contracts in deployment:

* NonFungibleToken
* MetadataViews
* FungibleTokenMetadataViews

And include the contract aliases in the flow.json of any scaffolding included on `flow init`

**Comment by turbolent** [comment]
Those contracts are deployed if the `--contracts` flag is passed:

```
$ flow emulator --contracts
INFO[0000] ⚙️   Using service account 0xf8d6e0586b0a20c7  serviceAddress=f8d6e0586b0a20c7 serviceHashAlgo=SHA3_256 servicePrivKey=e8641ea2aebcae5beadd5bc402c948c423f5aa8987ca1df30cf9694acbfa4174 servicePubKey=90c764b0d5f98cce993a27cebe071b93a2362b99ff8d08a5e29a66d4f202c1e34788f8ae2086bf6f623fa782514109962b174ac337fabc121c88712a2dde2eef serviceSigAlgo=ECDSA_P256
INFO[0000] 📜  Flow contract                              FlowFees=0xe5a8b7f23e8b548f
INFO[0000] 📜  Flow contract                              FlowStorageFees=0xf8d6e0586b0a20c7
INFO[0000] 📜  Flow contract                              FlowServiceAccount=0xf8d6e0586b0a20c7
INFO[0000] 📜  Flow contract                              FlowToken=0x0ae53cb6e3f42a79
INFO[0000] 📜  Flow contract                              FungibleToken=0xee82856bf20e2aa6
INFO[0000] 💵  FUSD contract                              FUSD=0xf8d6e0586b0a20c7
INFO[0000] ✨  NFT contract                               NonFungibleToken=0xf8d6e0586b0a20c7
INFO[0000] ✨  Metadata views contract                    MetadataViews=0xf8d6e0586b0a20c7
INFO[0000] ✨  Example NFT contract                       ExampleNFT=0xf8d6e0586b0a20c7
INFO[0000] ✨   NFT Storefront contract v2                NFTStorefrontV2=0xf8d6e0586b0a20c7
INFO[0000] ✨   NFT Storefront contract                   NFTStorefront=0xf8d6e0586b0a20c7
```

**Comment by turbolent** [comment]
It looks like only the `NonFungibleToken` `MetadataViews` contract is deployed, and the new `FungibleToken` `MetadataViews` contract needs to be added.

**Comment by alilloig** [comment]
What would be the cons of having all of them deployed by default instead of requiring the flag @sideninja? If it will make emulator slower or any other performance implications I like how the scaffolds sounds.

Probably adding the FungibleTokenSwitchboard will be nice too.

**Comment by alilloig** [comment]
Also, there maybe other contracts that get a lot of us and the community will enjoy of having them deployed just by specifying it on their flow.json or starting the emulator with a flag. I'm thinking about Lost and Found from Flowty or the USDC contract for example.

**Comment by bluesign** [comment]
@alilloig very good idea, only problem is maintaining this many contracts. I agree with @sideninja, scaffold is very nice solution for this.

**Comment by sideninja** [comment]
The very problem in my opinion is that this list of convenient contracts will grow indefinitely. I feel we have the tools you can easily deploy any contract you need to emulator by adding them to flow.json, what is obviously missing from making that easier is an easy way to get those contracts, and that will be solved with a "contract manager" that will get them for you automatically, which we have started to work on.
