### ISSUE TITLE
Format the contracts that is deployed a little better

### ISSUE THREAD

**Issue by bjartek** [onflow/flow-emulator#35]
### Issue To Be Solved

In the new 0.14.0 version of the cli i saw the following message in the log
INFO[0000] 📜  Flow contracts                             FlowFees=0xe5a8b7f23e8b548f FlowServiceAccount=0xf8d6e0586b0a20c7 FlowStorageFees=0xf8d6e0586b0a20c7 FlowToken=0x0ae53cb6e3f42a79 FungibleToken=0xee82856bf20e2aa6

It would be nice if those addreses where broken up to be a little nicer.

**Comment by bjartek** [comment]
Looks like this is not worth it or?

`
contracts := logrus.Fields{
		"FlowServiceAccount": chain.ServiceAddress().HexWithPrefix(),
		"FlowToken":          fvm.FlowTokenAddress(chain).HexWithPrefix(),
		"FungibleToken":      fvm.FungibleTokenAddress(chain).HexWithPrefix(),
		"FlowFees":           fvm.FlowFeesAddress(chain).HexWithPrefix(),
		"FlowStorageFees":    chain.ServiceAddress().HexWithPrefix(),
	}
	logger.WithFields(contracts).Infof("📜  Flow contracts")`

**Comment by sideninja** [comment]
The way lorgus logging works is formatting this way. Do you think still this is something worth addressing? It would require to make changes to formatting of the lorgus and on a quick look I haven't found simple way to customize `Fields` format.

**Comment by bjartek** [comment]
No if it is hard just close it.
