### ISSUE TITLE
Add support for `Block.view`

### ISSUE THREAD

**Issue by joshuahannan** [onflow/flow-emulator#36]
### Issue To Be Solved

The cadence built-in function `getCurrentBlock()` returns a `Block` struct that has the `view` field, but view is always zero.

### Suggest A Solution

* Make it so `getCurrentBlock().view` always returns the same value as `getCurrentBlock().height`

### Context

Somewhat blocking epoch smart contract testing, because the contract uses views to measure the passage of time.

**Comment by psiemens** [comment]
@joshuahannan Is this still a blocker for epochs testing?

**Comment by joshuahannan** [comment]
This is a blocker for being able to unit test the state machine with the emulator, but we've just been testing that part of it on localnet and benchnet, so it isn't a hard blocker for epochs

**Comment by sideninja** [comment]
Hi, @joshuahannan is this still relevant? I've tried to reproduce it but I actually get the correct non-zero value for the view property.

**Comment by joshuahannan** [comment]
I haven't tested it since I created this issue, so I don't know if it was ever fixed. @psiemens do you know?

**Comment by sideninja** [comment]
I can actually confirm the view property is not just returning zero but it has a value that is bigger or equal to the height which looks like it's working to me.
