### ISSUE TITLE
Accounts declared in the flow.json are not created when emulator is launched

### ISSUE THREAD

**Issue by cybercent** [onflow/flow-emulator#405]
### Instructions
`flow accounts create` adds and account to the `flow.json` file.

When relaunching the emulator the accounts defined in the `flow.json` are not recreated.

There should be a command to recreate the accounts defined in the `flow.json` file.

### Problem

Accounts defined in `flow.json` not present in emulator.

### Steps to Reproduce

```swift
{
	"accounts": {
		"AccountA": {
			"address": "01cf0e2f2f715450",
			"key": "some_private_key"
		},
		"AccountB": {
			"address": "179b6b1cb6755e31",
			"key": "some_private_key"
		},
		"AccountC": {
			"address": "f3fcd2c1a78f5eee",
			"key": "some_private_key"
		},
		"default": {
			"address": "01cf0e2f2f715450",
			"key": "some_private_key"
		},
		"emulator-account": {
			"address": "f8d6e0586b0a20c7",
			"key": "some_private_key"
		}
	},
	"deployments": {
		"emulator": {
			"default": [],
			"emulator-account": []
		}
	}
}
```

### Acceptance Criteria

There should be a command to recreate the accounts defined in the `flow.json` file.

### Context

<what are you currently working on that this is blocking?>

**Comment by bluesign** [comment]
This is a bit tricky subject, it falls to flow-cli's responsibility as we don't read flow json.

We experimented on this many times, but no solution was good enough. `flow dev` decided to move on to account agnostic side, same with testing frameworks. I think for now best option is to use snapshot feature ( with persist ) and then load your initial state from the snapshot.

**Comment by bluesign** [comment]
@janezpodhostnik I don't have permission but this seems like flow-cli issue, can you transfer to there to track better ?
