### ISSUE TITLE
FLOW_VERBOSE environment variable is no-longer respected

### ISSUE THREAD

**Issue by kaliweh-circle** [onflow/flow-emulator#414]
### Problem
The emulator no-longer respects the `FLOW_VERBOSE` environment variable (v.0.50.4). Without the verbose logging, debugging transaction issues is hard.

### Steps to Reproduce

Start the emulator using docker
```
docker run -p 3569:3569 -p 8080:8080 -e FLOW_HOST=0.0.0.0 -e FLOW_VERBOSE=true  gcr.io/flow-container-registry/emulator
```
The debug logs are no-longer written to stdout.

### Acceptance Criteria

The emulator respects the verbose flag and outputs the debug logs properly.

### Context
N/A

**Comment by bluesign** [comment]
Thanks for reporting, will investigate today
