### ISSUE TITLE
Inconsistent behavior between the emulator and the network

### ISSUE THREAD

**Issue by kaliweh-circle** [onflow/flow-emulator#415]
### Problem
Getting error `pending block with ID ...... is currently being executed` when attempting to send multiple transactions concurrently. I believe this used to work without issues in previous versions.

### Steps to Reproduce
Send multiple transactions concurrently and the second transaction will fail with error `io.grpc.StatusRuntimeException: INTERNAL: pending block with ID ... is currently being executed`

### Acceptance Criteria
The emulator mimics the real network behavior and doesn't throw an error when multiple transactions are sent concurrently  

### Context

N/A

**Comment by bluesign** [comment]
Thanks for reporting, I will check today.

**Comment by bluesign** [comment]
hey @kaliweh-circle , are you trying with some block time, or using default emulator launch?

**Comment by kaliweh-circle** [comment]
> hey @kaliweh-circle , are you trying with some block time, or using default emulator launch?

Hey @bluesign, I am running the emulator without setting a value for the block-time. This is no-longer an issue for me at but it could be very annoying for anyone trying to send transactions concurrently or at a high-rate. Thanks!

**Comment by bluesign** [comment]
thanks for the information @kaliweh-circle, problem here is real network is running with some block target / second. ( I think target is around 1 block / sec ) Here emulator have that option with block time. 

But default option is committing a new block after each transaction, but if you give some load ( more than emulator can process ) there is not a good solution here, as we have to commit a new block after each tx. I will try to come up with a solution but other option I can think of is wait for block to commit ( which will bottleneck the input there )

**Comment by bluesign** [comment]
Closing this for now, couldn't find a viable solution tbh, but I will keep in mind @kaliweh-circle
