### ISSUE TITLE
Exclude 'MetadataViews' from Default flow.json to Prevent Deployment Confusion

### ISSUE THREAD

**Issue by diegofornalha** [onflow/flow-emulator#480]
### Problem

[Forum](https://forum.onflow.org/t/clarification-on-error-message-when-deploying-contracts-in-flow-after-opening-flowser/5234/2)

When trying to deploy contracts in Flow using the flow deploy command, I encountered an error message indicating that the "MetadataViews" contract already exists in the "emulator-account". For those new to Flow development, this message can be confusing. The solution to this problem is simply to remove the "MetadataViews" from flow.json. However, when running the scaffold, the "MetadataViews" should not come by default, thus avoiding this kind of confusion.

### Steps to Reproduce

Run the scaffold in Flow.
Try to deploy contracts in Flow using the flow deploy command.
Observe the error message indicating that the "MetadataViews" contract already exists.
Acceptance Criteria
When running the scaffold, the "MetadataViews" should not come by default in flow.json.

### Context
I am working on the development and deployment of contracts in Flow. The default presence of "MetadataViews" in flow.json after running the scaffold is causing confusion.

**Comment by diegofornalha** [comment]
@bluesign It's better to change this issue to https://github.com/onflow/flow-cli ?

**Comment by chasefleming** [comment]
Not having it in the scaffold would actually be an issue on the scaffold and then updating the scaffold commit hash in the CLI. But I'm not sure I agree with this. All standards are deployed to the emulator by default. When moving to Testnet or Mainnet you'd most likely use the already deployed version as well so the local development route here follows the same path. Maybe this can be solved in a different way? Maybe there could be a different error or maybe there could be two scaffolds: one truly empty and one empty but with core contracts deployed? Also @diegofornalha would there have been a spot in the documentation that made this less confusing?

**Comment by diegofornalha** [comment]
@chasefleming You're absolutely right. After delving deeper into the subject, I've come to realize that this matter can be considered resolved from my end. The idea of having two different "scaffolds" is excellent and would certainly prevent misunderstandings. Thank you for shedding light on this, and I appreciate the constructive discussion.

**Comment by diegofornalha** [comment]
You're absolutely right. After delving deeper into the subject, I've come
to realize that this matter can be considered resolved from my end. The
idea of having two different "scaffolds" is excellent and would certainly
prevent misunderstandings. Thank you for shedding light on this, and I
appreciate the constructive discussion.

Em ter., 31 de out. de 2023 às 17:14, Chase Fleming <
***@***.***> escreveu:

**Comment by chasefleming** [comment]
Ok will think on that. And let me know if there could be any documentation or error that would further reduce the confusion. Thanks. Closing this.
