### ISSUE TITLE
Snapshot flag (`--snapshot`) doesn't automatically enable state persistance

### ISSUE THREAD

**Issue by bartolomej** [onflow/flow-emulator#490]
### Problem

I've noticed that when I run `flow emulator --snapshot`, created snapshots aren't persisted through emulator restarts, contrary to what [the documentation says](https://github.com/onflow/flow-emulator#configuration):

<img width="800" alt="Screenshot 2023-10-29 at 15 28 09" src="https://github.com/onflow/flow-emulator/assets/36109955/2d51c92b-977a-45dd-a485-e4dfabf1c09b">

### Steps to Reproduce

1. run `flow emulator --snapshot`
2. create a snapshot
3. restart the emulator
4. list snapshots endpoint returns null (http://localhost:8080/emulator/snapshots)

But when you run `flow emulator --snapshot --persist`, snapshots are persisted as expected.

### Acceptance Criteria

Snapshots are automatically persisted when `--snapshot` flag is used, as there is no use-case in using snapshots without persistence.

### Context

Working on implementing automatic project state saving (using snapshots) in Flowser.

**Comment by bluesign** [comment]
This is documentation bug actually, when emulator gained ability to do memory snapshots I forgot to fix this part of the documentation :(
