### ISSUE TITLE
Nit: Write error logs to os.Stderr

### ISSUE THREAD

**Issue by bartolomej** [onflow/flow-emulator#492]
### Issue To Be Solved

I noticed that error logs are written to stdout, where ideally I would expect them to be written to stderr.

This probably doesn't matter for the most part, but it would be helpful to tools that are trying to better understand emitted logs (e.g. detect and handle errors). 

### Suggest A Solution

I believe this could be achieved by using `zerolog.MultiLevelWriter` API (https://pkg.go.dev/github.com/rs/zerolog#readme-multiple-log-output) to redirect logs to either stdout or stderr (depending on their severity level).

### Context

[Flowser](https://github.com/onflowser/flowser) relies on the fact that error logs are emitted to stderr in certain places (e.g. to alert the user when emulator fails to start), so this would help us a bit in that regard.

**Comment by bluesign** [comment]
hmm we can add that, my only concern is if someone (or some tool )  is relying on existing behaviour.

**Comment by bluesign** [comment]
@bartolomej let me know if this works for you, if not we can try to find an alternative solution.

**Comment by bartolomej** [comment]
@bluesign Yeah, I think thay would work fine, will try it out soon.

I think we can close this issue for now.
