### ISSUE TITLE
Update emulator with the latest changes to the FlowDKG, FlowEpoch and FlowIDTableStaking contract

### ISSUE THREAD

**Issue by vishalchangrani** [onflow/flow-emulator#520]
## Instructions

There have been changes to the Flow core contracts - FlowDKG, FlowEpoch and FlowIDTableStaking.
Forum post describing the changes: https://forum.flow.com/t/upgrade-coming-to-flow-epoch-smart-contracts-for-performance-and-access-node-slots/5397
The emulator needs to be updated for the changes to the events emitted by FlowEpoch.EpochStart and the EpochSetup event.

**Comment by bluesign** [comment]
We are getting them from flow-go bootstrap, when switching to new flow-go version after it is updated, it should solve the problem.
