### ISSUE TITLE
Return computation used for scripts/transactinon on emulator

### ISSUE THREAD

**Issue by bjartek** [onflow/flow-emulator#526]
### Issue To Be Solved

When testing/desining scripts and transactions it is sometimes very hard to know how computation will scale as state grows. If there was a way to get this data from the emulator it would make life a lot easier. 

It is currently possible to get the meters for transactions but they are emitted as log entries and you have to parse the logs to get it out.

**Comment by bluesign** [comment]
Yesterday on Discord we had a discussion about fixes metering, I think we lack some stuff from Cadence side to make this useful. I have few ideas, today planning to discuss with Cadence team.
