### ISSUE TITLE
[Placeholder] Performance issues with large amount of transactions

### ISSUE THREAD

**Issue by janezpodhostnik** [onflow/flow-emulator#83]
### Issue To Be Solved

I have noticed that when running the emulator locally and sending a lot (thousands) of large transactions, it seems to slow down over time. 

I have no hard data to back this claim yet. I just want to open up this issue so if anyone else notices any performance issues they can 👍 the issue (or comment on it).

In case this is widely experienced. We should look into addressing the issue.

**Comment by bluesign** [comment]
This is fixed with new badger InMemory backend, I tried with 10k random transactions.
