### ISSUE TITLE
Unable to pass certain structures as arguments to scripts / transactions

### ISSUE THREAD

**Issue by briandilley** [onflow/flow-emulator#94]
We have an contract that has been working fine for a long time, and with the v0.28.4 version of the emulator it has stopped working. Specifically, structs exposed by the contract itself can no longer be passed into the contract as an argument for scripts and transactions. The contract can be found [here](https://gist.github.com/briandilley/b73fd9c8989bb3ed3d0b6fa16f2ff7d2). Specifically the `TenantService.MetadataField` struct cannot be used as an argument, but *only* when it contains a `TenantService.Mime` value.  For instance, the following script:

```
    import TenantService from .....
    pub fun main(metadata: TenantService.MetadataField): TenantService.MetadataField {
        return metadata
    }
```

passing the following value to it fails:
```
{
  "value": {
    "id": "A.0x02.TenantService.MetadataField",
    "fields": [
      {
        "name": "type",
        "value": {
          "value": {
            "id": "A.0x02.TenantService.MetadataFieldType",
            "fields": [
              {
                "name": "rawValue",
                "value": {
                  "value": "1",
                  "type": "UInt8"
                }
              }
            ]
          },
          "type": "Enum"
        }
      },
      {
        "name": "value",
        "value": {
          "value": {
            "id": "A.0x02.TenantService.Mime",
            "fields": [
              {
                "name": "type",
                "value": {
                  "value": "text/plain",
                  "type": "String"
                }
              },
              {
                "name": "bytes",
                "value": {
                  "value": [
                    {
                      "value": "32",
                      "type": "UInt8"
                    },
                    {
                      "value": "33",
                      "type": "UInt8"
                    },
                    {
                      "value": "34",
                      "type": "UInt8"
                    },
                    {
                      "value": "35",
                      "type": "UInt8"
                    },
                    {
                      "value": "36",
                      "type": "UInt8"
                    }
                  ],
                  "type": "Array"
                }
              }
            ]
          },
          "type": "Struct"
        }
      }
    ]
  },
  "type": "Struct"
}
```

What's interesting is that the following script works:
```
    import TenantService from .....
    pub fun main(mime: TenantService.Mime): TenantService.MetadataField {
        return TenantService.MetadataField(TenantService.MetadataFieldType.MIME, mime)
    }
```
You'll see that you can pass a `TenantService.Mime` into the contract but you can't pass it as a value on the `MetadataField` object (although other value types *do* work).

[Here's a link to the playground](https://play.onflow.org/93fab131-870f-4a0b-9c07-744963e0e86a?type=script&id=3a85a820-eb0f-4d49-a4e2-72d0da8267f8&storage=none) with the contract(s) deployed and a script that illustrates the problem Even the playground now has trouble with it.  Attached is an error from the javascript console of the web browser (there is no visual feedback of the error other than the JS console on the playground):

<img width="659" alt="Screen Shot 2021-11-10 at 5 17 02 PM" src="https://user-images.githubusercontent.com/1068495/141219732-fbc20643-f14d-4cf4-9fa0-01d488bb48cb.png">

**Comment by turbolent** [comment]
@briandilley Thank you for reporting this! You mentioned version v0.28.4, but no such release exists: https://github.com/onflow/flow-emulator/tags. Did you maybe mean a different version? 

Did you try this with an older release where it works?

**Comment by Kay-Zee** [comment]
It's possible that he means [v0.28.4](https://github.com/onflow/flow-cli/releases/tag/v0.28.4) for the CLI, which updates to [v0.24.0](https://github.com/onflow/flow-cli/pull/408/files) of the emulator

**Comment by briandilley** [comment]
@Kay-Zee  - yes, that's from `flow version`. I wasn't sure how to get the emulator version from that.

**Comment by sideninja** [comment]
I've reproduced the issue locally, but the same issue exists for previous versions of emulator and cli. The error I get reported is from Cadence:
```
❌ Command Error: failed to submit executable script: client: rpc error: code = Unknown desc = [Error Code: 1101] cadence runtime error Execution failed:
error: invalid argument at index 0: value does not conform to expected type `TenantService.MetadataField`
--> ed0c9b9d9a260dea5483730fec851a4887a9476cb9b745e705f1be5c020c85ea
```
I was using your JSON as argument
```
'[{"value":{"id":"A.f8d6e0586b0a20c7.TenantService.MetadataField","fields":[{"name":"type","value":{"value":{"id":"A.f8d6e0586b0a20c7.TenantService.MetadataFieldType","fields":[{"name":"rawValue","value":{"value":"1","type":"UInt8"}}]},"type":"Enum"}},{"name":"value","value":{"value":{"id":"A.f8d6e0586b0a20c7.TenantService.Mime","fields":[{"name":"type","value":{"value":"text/plain","type":"String"}},{"name":"bytes","value":{"value":[{"value":"32","type":"UInt8"},{"value":"33","type":"UInt8"},{"value":"34","type":"UInt8"},{"value":"35","type":"UInt8"},{"value":"36","type":"UInt8"}],"type":"Array"}}]},"type":"Struct"}}]},"type":"Struct"}]'
```
I think the JSON is in correct format.

**Comment by bluesign** [comment]
I think this is broken on https://github.com/onflow/flow-cli/releases/tag/v0.28.4

Works on my 0.28.3 on osx

**Comment by sideninja** [comment]
@bluesign I've pinned it down to emulator version 0.23.0 as being the one that breaks, so not the latest release but the one before. I will dig deeper what changed in that version.

**Comment by bluesign** [comment]
@sideninja yeah seems cadence array type issue. [UInt8] bytes imported as [Anystruct]

**Comment by sideninja** [comment]
> @sideninja yeah seems cadence array type issue. [UInt8] bytes field imported as [Anystruct]

Yes, I'm trying to create a test in Cadence to reproduce the issue, but I think @turbolent @SupunS should have context around this.

**Comment by SupunS** [comment]
Yeah, like bluesign mentioned, this is an issue in Cadence argument parsing.

This actually has two problems:
1. It tries to infer the type for the value of the inner field `bytes`, rather than taking the type from the enclosing struct definition (which should be `[UInt8]`)
2. Inferred type is not precise enough. This is a known limitation in the current implementation and is improved in: https://github.com/onflow/cadence/pull/1049

This would be fixed by fixing either one of the above. (Merging [cadence#1049](https://github.com/onflow/cadence/pull/1049) would fix this).
But at the same time, I would see if we can (1) as well.

---
A simple reproducing code:
```kotlin
pub fun main(v: AnyStruct) {
}

pub struct Foo {
    pub let bytes: [UInt8]

    init(_ bytes: [UInt8]) {
        self.bytes = bytes
    }
}
```

and pass:
```json
{
  "value": {
    "id": "S.test.Foo",
    "fields": [
      {
        "name": "bytes",
        "value": {
          "value": [
            {
              "value": "32",
              "type": "UInt8"
            }
          ],
          "type": "Array"
        }
      }
    ]
  },
  "type": "Struct"
}
```
